### ISSUE TITLE
question, how do you use this?

### ISSUE THREAD

**Issue by gbdavidx** [stef/smeter#2]
does it decode fsk?

**Comment by stef** [comment]
yes, it decodes the fsk modulated signal. it works with techem meters.

you pipe `capture.py` into either `baseband` or into `decode.py`. you can compile `baseband` using `gcc -o baseband -O2 baseband.c`.

**Comment by Marooned-MB** [comment]
I know it's a closed Issue but documentation of your work is a bit ascetic ;)

Looks like it needs Python 2,7 and not 3?

It also needs gnuradio module. In order to have that module I could not find a way to download it. All instructions tells about getting it from git and compiling. Compile requires Python3, so we have first inconsistency here. Also, it requires pybind11 however, when installing via `apt-get install python-pybind11` on Raspberry Pi (B rev 2), it fails to compile because `pybind11 version 2.2.4 < 2.4`.

So, in other words. Is there a simpler way to run this on Raspberry Pi (ARMv6)?

I bought rtl-sdr dongle to monitor my Techem heat and water meters and I'm stuck. I can see packets when using ` rtl_433 -f 868.95M` but it can't decode the data, just prints some field plus `Data` field with hexadecimal string.
I've also tried to use `wmbusmeters` but it can listen to only T or C types and I receive both from the meters. Also, the usage of `wmbusmeters` is quite enigmatic, didn't figure it out yet.

Any hint will be much appreciated. Thanks.

**Comment by stef** [comment]
in 6 years distance a lot of bitrot accrues on quickly mutating sw dependencies. i have no techem meter anymore.

i'm not sure what gnuradio module is needed, i don't remember this, and the code in capture/decode.py do not show anything special needed.

i can tell you that capture.py is a simple gnuradio component demodulating the signal, basically an osmocom source, fir filter, a squelch, a binary slicer and a quadrature demod. so that should be pretty easy to fix either for gnuradio3.7 or 3.8. https://github.com/stef/smeter/blob/master/techem.grc contains the gnuradio setup of this.

whatever comes out of capture.py needs to be piped into either decode.py, baseband or water.py, which dumps stuff in ascii. that's it. and compilation of baseband is actually as simple as in my previous comment:
> gcc -o baseband -O2 baseband.c

dunno what else to say. i guess wmbusmeters and maybe even rtl_433 do get you as far as the stuff rotting here. the only thing i can still recommend you is to write some decoder for the hex data dumped by rtl_433, there is a lot of docs available online, and the rest is a wonderful exercise in reverse engineering data protocols.

**Comment by Marooned-MB** [comment]
Yeah, thanks for your comment. Looks like wmbusmeters is a better choice now. Thanks!
